filebeat.inputs:
- type: filestream
  id: default-filestream
  paths:
    - ingest_data/*.log
- type: mqtt
  hosts:
      - ssl://65719a9fe79c489a973fe650f76c8088.s1.eu.hivemq.cloud:8883
  username: hivemq.webclient.1710319677860
  password: "4130CFABGdbEace;i,.:"
  topics: 
    - sensor_data
  
  index: 'sensor-data-%{+yyyy-MM-dd}'
  pipeline: sensor-data-geo

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_docker_metadata: ~

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD} 

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: "certs/ca/ca.crt"
  
